### ISSUE TITLE
owns property in IdentityDocument is not an array

### ISSUE THREAD

**Issue by yannick-beot-sp** [sailpoint-oss/api-specs#69]
According to the specs (cf. `idn/v3/schemas/search/model/identity/IdentityDocument.yaml`), `owns` is an array:

```
    owns:
      type: array
      description: Access items the identity owns. 
      items: 
        $ref: 'Owns.yaml'
```

Based on my tests, `owns` is actually an object: 

```
    "owns": {
        "accessProfiles": [
            {
                "id": "4f1baca895fa45ebada410ab40744330",
                "name": "Accounts Payable"
            },
            {
                "id": "c9478d6fc6f842dbaf572d08fda4b344",
                "name": "Accounts Receivable"
            },
            {
                "id": "fbb8b17d23284b5e8c802a84927d87dc",
                "name": "Financial Systems Analyst Access"
            }
        ]
    },
```
